services:
  # Backend Service (FastAPI)
  - type: web
    name: pdf-highlighter-backend
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Replace with your repo URL
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # Keep your API key secret
    healthCheckPath: /
    disk:
      name: data-disk
      mountPath: /app/data
      sizeGB: 1

  # Frontend Service (React Static Site)
  - type: static
    name: pdf-highlighter-frontend
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Replace with your repo URL
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://pdf-highlighter-backend.onrender.com # This will be your backend's live URL